version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: todo
  
  server:
    depends_on:
      - db
    build: ./ 
    restart: always
    ports:
     - 8080:8080
    environment:
     PG_CONN_STR: "host=db user=admin password=admin dbname=todo port=5432 sslmode=disable"